In [1]:
import numpy as np

In [2]:
arr = np.zeros(shape=(3,3), dtype=int)

arr[0][2] = 7
arr[0][1] = 7
arr[1][0]=1
arr[1][1]=1

arr

array([[0, 7, 7],
       [1, 1, 0],
       [0, 0, 0]])

In [3]:
values_row,counts_row = np.unique(arr[0,:], return_counts=True)
print(values_row)
print(counts_row)

[0 7]
[1 2]


In [4]:
piece = 1
alpha  = 0.4
beta = 0.4
omega = 0.2

values_row,counts_row = np.unique(arr[0,:], return_counts=True)
index_piece = np.where(values_row==piece)
index_other = np.where((values_row!=piece) & (values_row!=0))
index_0 = np.where(values_row==0)

values_col,counts_col = np.unique(arr[:,0], return_counts=True)
index_piece_col = np.where(values_col==piece)
index_other_col = np.where((values_col!=piece) & (values_col!=0))
index_0_col = np.where(values_col==0)


rows = np.sum(counts_row[index_piece])*alpha+(-np.sum(counts_row[index_other])*omega)**2 + index_0[0].shape[0] *beta
cols = np.sum(counts_col[index_piece_col])*alpha-np.sum(counts_col[index_other_col])*omega + index_0_col[0].shape[0]*beta
reward = rows+cols
arr2 = np.zeros(shape=(3,3))
arr2[0,np.where(arr[0,:]==0)] = reward



In [5]:
index_0

(array([0]),)

In [18]:
np.where(arr==0)[0].shape[0]

5

In [7]:
arr2

array([[1.36, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [11]:
arr2[1][2] = 10
arr2

array([[ 1.36,  0.  ,  0.  ],
       [ 0.  ,  0.  , 10.  ],
       [ 0.  ,  0.  ,  0.  ]])

In [12]:
np.argmax(arr2)

5

In [9]:
arr2[1]

array([0., 0., 0.])